export const BUILDING_LABELS: Record<string, string> = {
  sawmill:        'Aserradero',
  quarry:         'Cantera',
  grainFarm:      'Granja de Grano',
  windmill:       'Molino de Viento',
  cathedral:      'Catedral',
  workshop:       'Taller',
  engineersGuild: 'Gremio de Ingenieros',
  barracks:       'Barracones',
  granary:        'Granero',
  stonehouse:     'Casa de Piedra',
  silo:           'Silo',
  academy:        'Academia',
  alchemistTower: 'Torre del Alquimista',
  ambassadorHall: 'Salón de Embajadores',
  armoury:        'Armería',
}

export const RESEARCH_LABELS: Record<string, string> = {
  alchemy:          'Alquimia',
  pyromancy:        'Piromancia',
  runemastery:      'Maestría Rúnica',
  mysticism:        'Misticismo',
  dragonlore:       'Conocimiento Dracónico',
  swordsmanship:    'Esgrima',
  armoury:          'Armería',
  fortification:    'Fortificación',
  horsemanship:     'Equitación',
  cartography:      'Cartografía',
  tradeRoutes:      'Rutas Comerciales',
  spycraft:         'Arte del Espionaje',
  logistics:        'Logística',
  exploration:      'Exploración',
  diplomaticNetwork:'Red Diplomática',
  divineBlessing:   'Bendición Divina',
}

export const UNIT_LABELS: Record<string, string> = {
  squire:       'Escudero',
  knight:       'Caballero',
  paladin:      'Paladín',
  warlord:      'Señor de la Guerra',
  grandKnight:  'Gran Caballero',
  siegeMaster:  'Maestro de Asedio',
  warMachine:   'Máquina de Guerra',
  dragonKnight: 'Caballero Dragón',
  merchant:     'Mercader',
  caravan:      'Caravana',
  colonist:     'Colonista',
  scavenger:    'Saqueador',
  scout:        'Explorador',
  beacon:       'Faro',
  archer:       'Arquero',
  crossbowman:  'Ballestero',
  ballista:     'Ballista',
  trebuchet:    'Trebuchet',
  mageTower:    'Torre Maga',
  dragonCannon: 'Cañón Dragón',
  palisade:     'Palizada',
  castleWall:   'Muralla',
  moat:         'Foso',
  catapult:     'Catapulta',
}

export function label(id: string): string {
  return BUILDING_LABELS[id] ?? RESEARCH_LABELS[id] ?? UNIT_LABELS[id] ?? id
}
